### ISSUE TITLE
Error fetching key E1F958385BFE2B6E from keyserver: keys.gnupg.net

### ISSUE THREAD

**Issue by semla** [don-rumata/ansible-role-install-x2go#1]
I am getting the error below:

```
TASK [x2go : apt_key] *******************************************************************************************************************************************************
task path: /home/user/.ansible/roles/x2go/tasks/add-repo.yml:13
fatal: [root@xxx.xx.xx.xxx]: FAILED! => {
    "changed": false,
    "cmd": "/usr/bin/apt-key adv --no-tty --keyserver keys.gnupg.net --recv E1F958385BFE2B6E",
    "forced_environment": {
        "LANG": "C",
        "LC_ALL": "C",
        "LC_MESSAGES": "C"
    },
    "invocation": {
        "module_args": {
            "data": null,
            "file": null,
            "id": "E1F958385BFE2B6E",
            "key": null,
            "keyring": null,
            "keyserver": "keys.gnupg.net",
            "state": "present",
            "url": null,
            "validate_certs": true
        }
    },
    "msg": "Error fetching key E1F958385BFE2B6E from keyserver: keys.gnupg.net",
    "rc": 2,
    "stderr": "Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).\ngpg: keyserver receive failed: Server indicated a failure\n",
    "stderr_lines": [
        "Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).",
        "gpg: keyserver receive failed: Server indicated a failure"
    ],
    "stdout": "Executing: /tmp/apt-key-gpghome.uCGF8qmvIk/gpg.1.sh --no-tty --keyserver keys.gnupg.net --recv E1F958385BFE2B6E\n",
    "stdout_lines": [
        "Executing: /tmp/apt-key-gpghome.uCGF8qmvIk/gpg.1.sh --no-tty --keyserver keys.gnupg.net --recv E1F958385BFE2B6E"
    ]
}

```

**Comment by don-rumata** [comment]
Try changing the file `/home/user/.ansible/roles/x2go/tasks/add-repo.yml`:

v1:

```yaml
    - apt_key:
        # keyserver: keys.gnupg.net
        # id: E1F958385BFE2B6E
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x972fd88fa0bafb578d0476dfe1f958385bfe2b6e
        state: present
```

v2:

```yaml
    - apt_key:
        keyserver: keyserver.ubuntu.com
        id: E1F958385BFE2B6E
        state: present
```
